Vagrant.configure("2") do |config|

  # Máquina Servidor Web
  config.vm.define :servidor_web do |web|
    web.vm.box = "debian/bookworm64"
    web.vm.hostname = "servidor-web"
    web.vm.synced_folder ".", "/vagrant", disabled: true
    web.vm.network :private_network,
      :libvirt__network_name => "red_aislada",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.1",
      :libvirt__forward_mode => "veryisolated"
    
    # Provisionar Apache en el servidor
    web.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
      a2enmod rewrite
      systemctl enable apache2
      systemctl start apache2
    SHELL
  end

  # Máquina Cliente
  config.vm.define :cliente do |cliente|
    cliente.vm.box = "debian/bookworm64"
    cliente.vm.hostname = "cliente"
    cliente.vm.synced_folder ".", "/vagrant", disabled: true
    cliente.vm.network :private_network,
      :libvirt__network_name => "red_aislada",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.2",
      :libvirt__forward_mode => "veryisolated"
    
    # Provisionar Apache en el cliente (si es necesario)
    cliente.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL
  end
end
