---
- name: Actualizar repositorios
  apt:
    update_cache: yes

- name: Instalar dependencias de WordPress
  apt:
    name:
      - php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
    state: present

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Eliminar contenido anterior
  file:
    path: /var/www/html/index.html
    state: absent

- name: Configurar permisos de WordPress
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Copiar archivo de configuración de WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data

- name: Asegurar que el módulo rewrite está habilitado
  apache2_module:
    name: rewrite
    state: present
  notify: Reiniciar Apache

- name: Configurar Apache para WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Reiniciar Apache
