- name: Eliminar ruta por defecto existente
  command: ip route del default
  ignore_errors: yes

- name: Configurar nueva ruta por defecto
  command: ip route add default via {{ ip_interna_router }} dev eth1
