- name: Eliminar ruta por defecto existente
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^\s*post-up ip route add default.*'
    state: absent

- name: Añadir nueva ruta por defecto
  lineinfile:
    path: /etc/network/interfaces
    insertafter: '^\s*post-up ip route del default.*'
    line: '    post-up ip route add default via {{ip_interna_router}} dev eth1'
    state: present

