- name: Eliminar ruta por defecto existente en el router
  command: ip route delete default
  ignore_errors: yes

- name: Añadir nueva ruta por defecto en el router
  command: ip route add default via {{ gateway_internet_router }} dev {{ public_interface }}

- name: Cambiar el bit de forward a 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Limpiar reglas de iptables existentes
  iptables:
    flush: yes
    table: "{{ item }}"
  loop:
    - filter
    - nat
    - mangle
  become: yes

- name: Configurar DNAT para el servidor web
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ public_interface }}"
    protocol: tcp
    destination_port: 80
    jump: DNAT
    to_destination: "{{ ip_interna_web }}:80"
  become: yes

- name: Configurar SNAT para la red interna
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ public_interface }}"
    source: "{{ ip_interna_local }}/24"
    jump: MASQUERADE
  become: yes

- name: Guardar reglas de iptables
  shell: iptables-save > /etc/iptables/rules.v4
  become: yes
