- name: Instalar paquetes necesarios
  apt:
    name:
      - iptables
      - net-tools
      - dnsutils
      - iptables-persistent
    state: present

- name: Habilitar el reenvío de IP
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Configurar SNAT
  command: iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
  notify:
    - Reiniciar iptables

- name: Configurar DNAT
  command: iptables -t nat -A PREROUTING -p tcp -d {{ public_ip }} --dport 80 -j DNAT --to-destination 10.0.0.2:80
  notify:
    - Reiniciar iptables

- name: Guardar reglas de iptables
  shell: iptables-save
  register: iptables_rules

- name: Escribir reglas en archivo
  copy:
    content: "{{ iptables_rules.stdout }}"
    dest: /etc/iptables/rules.v4
    mode: '0644'
  notify: Reiniciar iptables

- name: Eliminar la ruta existente (si existe)
  command: ip route del 10.0.0.0/24
  ignore_errors: yes

- name: Configurar rutas para la red interna
  command: ip route add 10.0.0.0/24 via 10.0.0.1


