Vagrant.configure("2") do |config|
  # Usar una caja de Debian
  config.vm.box = "debian/bullseye64"

  # Asignar una IP estática dentro de la red 172.22.200.0/24
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "172.22.200.69"

  # Configurar nombre de la máquina
  config.vm.hostname = "cliente"

  # Configuración de la máquina
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
end

